# Working with Numpy

## Why we use numpy inseated of list

### Demonstration of Consuming Less memory by Numpy , Fast and Convenient

In [1]:
import numpy as np
import math as ml
import time
import sys

In [2]:
li = range(100)
print(li)

range(0, 100)


In [3]:
print(sys.getsizeof(2)*len(li))

2800


In [4]:
a = np.arange(100)
print(a.size*a.itemsize)

400


In [5]:
s= 1000000
l1 = range(s)
l2 = range(s)
start = time.time()
l3 = [(x,y)for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

393.7568664550781


In [6]:
a1 = np.arange(s)
a2 = np.arange(s)
start = time.time()
a3 = a1+a2
print((time.time()-start)*1000)

5.9967041015625


# Array Creation: Conversion from other python structure 

In [7]:
### Creating numpy array using list
li = [2,6,888],[6,5,9],[6,5,4]
li2 = [2,5,8], [5,7,8],[6,7,1]
li1 = np.array(li,np.int32)
li3 = np.array(li2)
print(li)
print(type(li))
print(li1, li3)
print(type(li1))
li1.dtype
print(li1.ndim)

([2, 6, 888], [6, 5, 9], [6, 5, 4])
<class 'tuple'>
[[  2   6 888]
 [  6   5   9]
 [  6   5   4]] [[2 5 8]
 [5 7 8]
 [6 7 1]]
<class 'numpy.ndarray'>
2


In [8]:
#Find the dimension of an Array
arr = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)],np.int16)
a = np.array([1,2,3])
print(a.ndim)
print(arr.ndim)

1
2


In [9]:
#Find the byte size of each of the array element
print(arr.itemsize)
print(a.itemsize)

2
4


In [10]:
#FInd the data type or dtype of array
print(arr.dtype)
print(a.dtype)

int16
int32


In [11]:
#Find the size of Array
print(a.size)
print(arr.size)

3
15


In [12]:
#find the shape of array
print(a.shape)
print(arr.shape)

(3,)
(3, 5)


In [13]:
# Arrays creation using zeros() method
z = np.zeros(5)
print(z)
z1 =np.zeros([3,3,3], dtype =  np.int32)
print(z1)
print(type(z1))
z1.dtype

[0. 0. 0. 0. 0.]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
<class 'numpy.ndarray'>


dtype('int32')

In [14]:
#Array creations using ones() method
o = np.ones(3, dtype = np.int16)
print(o)
o1 = np.ones((4,4,2))
print(o1)


[1 1 1]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [15]:
# Array Creation using full() methods
f = np.full(3,2)
print(f)
f1 =np.full((3,2),4)
print(f1)

[2 2 2]
[[4 4]
 [4 4]
 [4 4]]


In [16]:
# Array creations using empty() funtion
e = np.empty(3)
print(e)
e.dtype
e1 = np.empty([4,2])
print(e1)
print("Round ndarray upto decimal places",np.around(e1, decimals=1))

[8.83803888e-312 0.00000000e+000 4.94065646e-324]
[[0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000]
 [0.0e+000 6.8e-321]
 [0.0e+000 0.0e+000]]
Round ndarray upto decimal places [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
ar= np.arange(10)
print(ar)
ar1= np.arange(1,10,2)
print(ar1)
for a in range(1,10,2):
    print(a)
print(ar1.dtype)

print(type(a))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
1
3
5
7
9
int32
<class 'int'>


In [18]:
# Generate Random float
rf = np.random.rand(10)   # 1-D arrays using Random function
print(rf)

[0.16734496 0.21101985 0.59566183 0.21978524 0.65148206 0.69382717
 0.62843358 0.1606262  0.6915412  0.51481418]


In [19]:
#Generate 2-D array using random float
rf1= np.random.rand(3,3)
print(rf1, rf1.ndim)


[[0.86792896 0.44981102 0.5840064 ]
 [0.35697908 0.79279106 0.61132729]
 [0.3424443  0.587851   0.50384064]] 2


In [20]:
#generate 1 d array containg random integers
ri= np.random.randint(1,10,3)
print(ri)

[6 2 2]


In [21]:
#Numpy array creation using linspace() function
ali = np.linspace(1,10,5, retstep= True, endpoint= True)
print(ali)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


# Numpy array Indexing

In [22]:
# Accessing 1-D array elements
arr = np.array([1,23,4,50])
print(arr[0])  # Get the first elements from the array
print(arr[3])  # gets the fourth element from the array

1
50


In [23]:
arr1 = np.array([1,23,4,50])
print(arr1[0]+arr1[3]) # gets first element and fourth element from the array add them

51


In [24]:
# Accessing 2-D Array
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(' 3rd element on 1st dimension:-',arr3[0,2])        

 3rd element on 1st dimension:- 3


In [25]:
# Accessing 2-D Array
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(' 4th element on 2nd dimension:-',arr3[1,3]) 

 4th element on 2nd dimension:- 9


In [26]:
# Accessing 3-D Array
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,87,9],[10,11,12]]])
print(arr5[0,1,2])
print(arr5[1,0,-2])

6
87


# Numpy Array Slilcing

In [27]:
#Slicing elements 
import numpy as np
sarr1= np.array([1,2,3,4,5,6,7])
print(sarr1[0:5])
print(sarr1[5:])
print(sarr1[:5])
print(sarr1[-3:-1])

[1 2 3 4 5]
[6 7]
[1 2 3 4 5]
[5 6]


In [28]:
#slicing arrays using step
sarr2= np.array([1,2,3,4,5,6,7])
print(sarr2[1:5:2])
print(sarr2[::2])

[2 4]
[1 3 5 7]


In [29]:
sarr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(sarr3[1,1:4:3])
print(sarr3[0:2,1:2])

[7]
[[2]
 [7]]


In [30]:
# Basic operation using scalars
import numpy as np
a = np.array([1,2,3,4,5])
print(a+100)

[101 102 103 104 105]


In [31]:
# Basic operation using scalars
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1*10)

[10 20 30 40 50]


In [32]:
# Basic operation using scalars
import numpy as np
a2 = np.array([1,2,3,4,5])
print(a2-100)

[-99 -98 -97 -96 -95]


In [33]:
# Basic operation using scalars
import numpy as np
a2 = np.array([1,2,3,4,5])
a3 = np.array([1,2,3,4,5])
print(a2/2)

[0.5 1.  1.5 2.  2.5]


In [34]:
# Basic operation using scalars
import numpy as np
a2 = np.array([1,2,3,4,5])
a3 = np.array([1,2,3,4,5])
print(a3%2)

[1 0 1 0 1]


# Using Numpy Function

In [35]:
#Using numpy fuction add(), subtract(),, multiply(),divide(),mod() or remainder()
import numpy as np
ab = np.arange(9).reshape(3,3)
bb = np.array([10,10,10])
print("Array First:")
print(ab)
print("Add the two arrays:-")
print(np.add(ab,bb))
print("Subtract the two arrays:-")
print(np.subtract(ab,bb))
print("multiply the two arrays:-")
print(np.multiply(ab,bb))
print("Divide the two arrays:-")
print(np.divide(ab,bb))

Array First:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Add the two arrays:-
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Subtract the two arrays:-
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]
multiply the two arrays:-
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
Divide the two arrays:-
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [36]:
# Using Power ()function
ab1 = np.arange(9).reshape(3,3)
bb1 = np.array([10,10,10])
c = np.power(ab1,bb1)
print(c)


[[         0          1       1024]
 [     59049    1048576    9765625]
 [  60466176  282475249 1073741824]]


In [37]:
#Using mod(),fmod(),remainder() function
p = np.array([10,20,30,40,50,60])
q = np.array([13,5,6,7,8,12])
pq = np.mod(p,q)
print("Mod/Remainder of the value:",pq)
qp= np.remainder(p,q)
print("Remainder of the value:",qp)
p1 = np.fmod(p,q)
print("Mod/Remainder of the value:",p1)
p2 = np.divmod(p,q)
print("Returns Remainder and quotient of the value:",p2)

Mod/Remainder of the value: [10  0  0  5  2  0]
Remainder of the value: [10  0  0  5  2  0]
Mod/Remainder of the value: [10  0  0  5  2  0]
Returns Remainder and quotient of the value: (array([0, 4, 5, 5, 6, 5], dtype=int32), array([10,  0,  0,  5,  2,  0], dtype=int32))


In [38]:
#using log, log2, log10 functions
r = np.array([10,20,30,40,50,60])
print("Natural Log", np.log(r))
print("Log base 2",np.log2(r))
print("Log base 10",np.log10(r))

Natural Log [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301 4.09434456]
Log base 2 [3.32192809 4.32192809 4.9068906  5.32192809 5.64385619 5.9068906 ]
Log base 10 [1.         1.30103    1.47712125 1.60205999 1.69897    1.77815125]


In [71]:
#using sqrt, square functions
r1 = np.array([10,20,25,40,50,60], dtype = int)
print(r1.dtype)
print("Square root", np.around(np.sqrt(r1), decimals = 1))
print("Square", np.square(r1))

int32
Square root [3.2 4.5 5.  6.3 7.1 7.7]
Square [ 100  400  625 1600 2500 3600]


# Sum, MIn and max Methods of NUmpy Array

In [40]:
import numpy as np
num = np.array([100,200,300])
print("Sum of Arrary Elements", num.sum())
print("Maximum value in Array:",num.max())
print("Minimum Value in Array:", num.min())
print(num.sum(axis=0))

Sum of Arrary Elements 600
Maximum value in Array: 300
Minimum Value in Array: 100
600


In [42]:
num1 = np.array([[100,200,300],[200,300,400]])
print(num1)
print(num1.shape)
a = num1.reshape(3,2)
print(a)
print(a.shape)
print(a.sum(axis=1))
print(a.sum(axis=0))
print(a.mean())


[[100 200 300]
 [200 300 400]]
(2, 3)
[[100 200]
 [300 200]
 [300 400]]
(3, 2)
[300 500 700]
[700 800]
250.0


In [66]:
ax = np.arange(0,10).reshape(5,2)
ax1= ax.reshape(2,5)
ax2= ax.reshape(5,2)
print(ax1)
print(ax2)
print(ax.ravel())
print(ax1.T)
print(ax2.transpose())
print(ax)
print(ax.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


# Joining Numpy Arrary Using vstack() and hstack() mehtod

In [75]:
import numpy as np
av = np.array([[1,2,3],[2,3,4]])
av1= np.array([[5,6,7],[8,9,10]])
vst = np.vstack((av,av1))
print("array1",av)
print("array2",av1)
print("Combining arrays vertically:")
print(vst)
hst = np.hstack((av,av1))
print("Combining arrays horzontally:\n",hst)
               

array1 [[1 2 3]
 [2 3 4]]
array2 [[ 5  6  7]
 [ 8  9 10]]
Combining arrays vertically:
[[ 1  2  3]
 [ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Combining arrays horzontally:
 [[ 1  2  3  5  6  7]
 [ 2  3  4  8  9 10]]


In [2]:
#combining arrays using concatenate() method
import numpy as np
ar1 = np.arange(5)
ar2 = np.arange(5,10)
ar3 = np.concatenate((ar1,ar2))
print(ar1,ar2)
print(ar3)

[0 1 2 3 4] [5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
a = np.arange(1,9).reshape(2,-1)
p1,p2 = np.hsplit(a,2)
print(a)
print(p1)
print(p2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [5]:
np.vsplit(a,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [10]:
np.split(a,(2,4))

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [19]:
np.loadtxt('data.txt', dtype= int, delimiter = ',')

array([[100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7]])

In [22]:
np.genfromtxt('data.txt',dtype = int, delimiter=',', skip_footer = 3)

array([[100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7],
       [100, 200,   4,   5,   6,   7]])

In [32]:
newarr= np.genfromtxt('std123.txt',dtype = int, delimiter=',',skip_header=1)

In [33]:
np.savetxt("test.txt",newarr, delimiter= ',')