# Working with Numpy

## Why we use numpy inseated of list

### Demonstration of Consuming Less memory by Numpy , Fast and Convenient

In [1]:
import numpy as np
import math as ml
import time
import sys

In [2]:
li = range(100)
print(li)

range(0, 100)


In [3]:
print(sys.getsizeof(2)*len(li))

2800


In [4]:
a = np.arange(100)
print(a.size*a.itemsize)

400


In [5]:
s= 1000000
l1 = range(s)
l2 = range(s)
start = time.time()
l3 = [(x,y)for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

503.68738174438477


In [6]:
a1 = np.arange(s)
a2 = np.arange(s)
start = time.time()
a3 = a1+a2
print((time.time()-start)*1000)

3.9980411529541016


# Array Creation: Conversion from other python structure 

In [7]:
### Creating numpy array using list
li = [2,6,888],[6,5,9],[6,5,4]
li2 = [2,5,8], [5,7,8],[6,7,1]
li1 = np.array(li,np.int32)
li3 = np.array(li2)
print(li)
print(type(li))
print(li1, li3)
print(type(li1))
li1.dtype
print(li1.ndim)

([2, 6, 888], [6, 5, 9], [6, 5, 4])
<class 'tuple'>
[[  2   6 888]
 [  6   5   9]
 [  6   5   4]] [[2 5 8]
 [5 7 8]
 [6 7 1]]
<class 'numpy.ndarray'>
2


In [8]:
#Find the dimension of an Array
arr = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)],np.int16)
a = np.array([1,2,3])
print(a.ndim)
print(arr.ndim)

1
2


In [9]:
#Find the byte size of each of the array element
print(arr.itemsize)
print(a.itemsize)

2
4


In [10]:
#FInd the data type or dtype of array
print(arr.dtype)
print(a.dtype)

int16
int32


In [11]:
#Find the size of Array
print(a.size)
print(arr.size)

3
15


In [12]:
#find the shape of array
print(a.shape)
print(arr.shape)

(3,)
(3, 5)


In [13]:
# Arrays creation using zeros() method
z = np.zeros(5)
print(z)
z1 =np.zeros([3,3,3], dtype =  np.int32)
print(z1)
print(type(z1))
z1.dtype

[0. 0. 0. 0. 0.]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
<class 'numpy.ndarray'>


dtype('int32')

In [14]:
#Array creations using ones() method
o = np.ones(3, dtype = np.int16)
print(o)
o1 = np.ones((4,4,2))
print(o1)


[1 1 1]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [15]:
# Array Creation using full() methods
f = np.full(3,2)
print(f)
f1 =np.full((3,2),4)
print(f1)

[2 2 2]
[[4 4]
 [4 4]
 [4 4]]


In [16]:
# Array creations using empty() funtion
e = np.empty(3)
print(e)
e.dtype
e1 = np.empty([4,2])
print(e1)

[1.01850059e-311 1.01850059e-311 1.01850059e-311]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.89715642e-321]
 [1.01643598e-311 1.01643598e-311]]


In [17]:
ar= np.arange(10)
print(ar)
ar1= np.arange(1,10,2)
print(ar1)
for a in range(1,10,2):
    print(a)
print(ar1.dtype)

print(type(a))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
1
3
5
7
9
int32
<class 'int'>


In [18]:
# Generate Random float
rf = np.random.rand(10)   # 1-D arrays using Random function
print(rf)

[0.74595637 0.68831842 0.20551249 0.14828308 0.48056536 0.77967943
 0.28257049 0.91706843 0.8575031  0.9392032 ]


In [19]:
#Generate 2-D array using random float
rf1= np.random.rand(3,3)
print(rf1, rf1.ndim)


[[0.46429762 0.93137709 0.14808271]
 [0.22859274 0.29604983 0.52039509]
 [0.64863648 0.00344112 0.66105728]] 2


In [20]:
#generate 1 d array containg random integers
ri= np.random.randint(1,10,3)
print(ri)

[3 3 9]


In [32]:
#Numpy array creation using linspace() function
ali = np.linspace(1,10,5, retstep= True, endpoint= True)
print(ali)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


# Numpy array Indexing

In [34]:
# Accessing 1-D array elements
arr = np.array([1,23,4,50])
print(arr[0])  # Get the first elements from the array
print(arr[3])  # gets the fourth element from the array

1
50


In [35]:
arr1 = np.array([1,23,4,50])
print(arr1[0]+arr1[3]) # gets first element and fourth element from the array add them

51


In [40]:
# Accessing 2-D Array
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(' 3rd element on 1st dimension:-',arr3[0,2])        

 3rd element on 1st dimension:- 3


In [41]:
# Accessing 2-D Array
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(' 4th element on 2nd dimension:-',arr3[1,3]) 

 4th element on 2nd dimension:- 9


In [44]:
# Accessing 3-D Array
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,87,9],[10,11,12]]])
print(arr5[0,1,2])
print(arr5[1,0,-2])

6
87


# Numpy Array Slilcing

In [7]:
#Slicing elements 
import numpy as np
sarr1= np.array([1,2,3,4,5,6,7])
print(sarr1[0:5])
print(sarr1[5:])
print(sarr1[:5])
print(sarr1[-3:-1])

[1 2 3 4 5]
[6 7]
[1 2 3 4 5]
[5 6]


In [14]:
#slicing arrays using step
sarr2= np.array([1,2,3,4,5,6,7])
print(sarr2[1:5:2])
print(sarr2[::2])

[2 4]
[1 3 5 7]


In [27]:
sarr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(sarr3[1,1:4:3])
print(sarr3[0:2,1:2])

[7]
[[2]
 [7]]
